acceleration:
  name: acceleration-dv
  replicaCount: 2
  container:
    image: wasimakram27836/accelaration-dv:2.0
    port: 3001
  service:
    type: ClusterIP
    port: 3001
    targetPort: 3001
  ingress:
    enabled: false
