acceleration:
  name: acceleration-a
  replicaCount: 2
  container:
    image: wasimakram27836/accelaration-a:2.1
    port: 3002
  service:
    type: ClusterIP
    port: 3002
    targetPort: 3002
  ingress:
    enabled: false

