acceleration:
  name: acceleration-calc
  replicaCount: 2
  container:
    image:  wasimakram27836/accelaration-calc:2.0
    port: 3000
    env:
      DV_URL: "http://acceleration-dv:3001/dv"
      A_URL: "http://acceleration-a:3002/a"
  service:
    type: NodePort
    port: 3000
    targetPort: 3000
  ingress:
    enabled: false

